export const
    breadcrumbs = {
        "" : "Домашняя страница",
        "graphs": "Граф классификатора",
        "instruction": "Инструкция",
        "profiles": "Профили ученых",
        "ratings": "Тематическое ранжирование",
        "thesaurus": "Граф глоссария",
        "distances": "Расстояния",
        "profile": "Профиль",
        "search": "Текстовый поиск",
        "sResult": "Результаты",
        "dResult": "Результаты",
        "uploading": "Загрузка публикации",
        "author": "Автор",
        "conference": "Конференция",
        "journal": "Журнал",
        "organization": "Организация",
        "publication": "Публикация",
        "isand_publ": "Публикация",
        "deepSearch": "Тематический поиск",
        "glossary": "Глоссарий",
        "personality": "Личная страница",
        "setting": "Изменение страниц",
        "upload": "Загрузка публикаций",
        "authors": "Список авторов",
        "publications": "Список публикаций",
        "tmpPage": "Временная страница", 
        "authorr": "Автор",
        "account": "Личная страница"
    }